CREATE TABLE IF NOT EXISTS sensor_packets (
 id BIGSERIAL PRIMARY KEY, machine_id TEXT NOT NULL, timestamp TIMESTAMPTZ NOT NULL,
 rpm DOUBLE PRECISION NOT NULL, vibration DOUBLE PRECISION NOT NULL,
 temperature DOUBLE PRECISION NOT NULL, current DOUBLE PRECISION NOT NULL,
 status TEXT NOT NULL, risk DOUBLE PRECISION NOT NULL DEFAULT 0,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS events (
 id BIGSERIAL PRIMARY KEY, machine_id TEXT NOT NULL, type TEXT NOT NULL,
 severity TEXT NOT NULL, message TEXT NOT NULL, timestamp TIMESTAMPTZ NOT NULL
);
CREATE TABLE IF NOT EXISTS maintenance (
 id BIGSERIAL PRIMARY KEY, machine_id TEXT NOT NULL, action TEXT NOT NULL,
 priority TEXT NOT NULL, status TEXT NOT NULL, due_at TIMESTAMPTZ,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS batches (
 id BIGSERIAL PRIMARY KEY, batch_id TEXT UNIQUE NOT NULL, machine_id TEXT NOT NULL,
 quantity INTEGER NOT NULL, good INTEGER NOT NULL DEFAULT 0, reject INTEGER NOT NULL DEFAULT 0,
 started_at TIMESTAMPTZ NOT NULL, completed_at TIMESTAMPTZ
);